import 'package:collection/collection.dart';
import 'package:flutter/material.dart';
import 'package:sound_center/features/stream/data/source/radio_browser.dart';
import 'package:sound_center/generated/l10n.dart';
import 'package:sound_center/shared/widgets/loading.dart';
import 'package:sound_center/shared/widgets/text_field_box.dart';

class TagListDialog extends StatefulWidget {
  const TagListDialog({super.key, this.currentTag});

  final String? currentTag;

  @override
  State<TagListDialog> createState() => _TagListDialogState();
}

class _TagListDialogState extends State<TagListDialog> {
  List<Map<String, dynamic>> raw = [];
  late List<Map<String, dynamic>> searchTags;
  late final TextEditingController query;
  Map? current;

  @override
  void initState() {
    query = TextEditingController();
    _init();
    super.initState();
  }

  @override
  void dispose() {
    query.dispose();
    super.dispose();
  }

  Future<void> _init() async {
    final tags = await RadioBrowser().getTags();

    if (tags != null) {
      raw =
          tags
              .where((c) => c.name.trim().isNotEmpty)
              .map((c) => {'name': c.name, 'stationCount': c.stationCount})
              .toList()
            ..sort(
              (a, b) => (a['name'] as String).compareTo(b['name'] as String),
            );
    } else {
      raw = [
        {"name": "00's"},
        {"name": "00s"},
        {"name": "100.1 fm"},
        {"name": "100.3 fm"},
        {"name": "101.3 fm"},
        {"name": "101.7 fm"},
        {"name": "102.5 fm"},
        {"name": "102.9 fm"},
        {"name": "103.3 fm"},
        {"name": "103.7 fm"},
        {"name": "103.9 fm"},
        {"name": "104.1 fm"},
        {"name": "104.5 fm"},
        {"name": "104.9 fm"},
        {"name": "106.1 fm"},
        {"name": "107.9 fm"},
        {"name": "10s"},
        {"name": "128 kbit/s"},
        {"name": "1940s"},
        {"name": "1950s"},
        {"name": "1960s"},
        {"name": "1970s"},
        {"name": "1980's"},
        {"name": "1980s"},
        {"name": "1980s hits"},
        {"name": "1990s"},
        {"name": "2000's"},
        {"name": "2000er"},
        {"name": "2000s"},
        {"name": "2010s"},
        {"name": "2020s"},
        {"name": "20s"},
        {"name": "24/7"},
        {"name": "50s"},
        {"name": "540 am"},
        {"name": "5g智慧电台"},
        {"name": "60's"},
        {"name": "60er"},
        {"name": "60s"},
        {"name": "64kbps"},
        {"name": "70 80 hits"},
        {"name": "70's"},
        {"name": "70er"},
        {"name": "70s"},
        {"name": "70s disco"},
        {"name": "80"},
        {"name": "80's"},
        {"name": "80er"},
        {"name": "80s"},
        {"name": "80s en español"},
        {"name": "80s rock"},
        {"name": "88.1 fm"},
        {"name": "88.5 fm"},
        {"name": "89.3 fm"},
        {"name": "89.7 fm"},
        {"name": "89.9 fm"},
        {"name": "90"},
        {"name": "90's"},
        {"name": "90.1 fm"},
        {"name": "90.5 fm"},
        {"name": "90.9 fm"},
        {"name": "90er"},
        {"name": "90s"},
        {"name": "90s dance"},
        {"name": "90s y más"},
        {"name": "91.7 fm"},
        {"name": "92.1 fm"},
        {"name": "92.3 fm"},
        {"name": "92.5 fm"},
        {"name": "92.9 fm"},
        {"name": "93.1 fm"},
        {"name": "93.3 fm"},
        {"name": "95.3 fm"},
        {"name": "95.7 fm"},
        {"name": "96.1 fm"},
        {"name": "96.3 fm"},
        {"name": "96.9 fm"},
        {"name": "98.1 fm"},
        {"name": "98.5 fm"},
        {"name": "98.9 fm"},
        {"name": "99.3 fm"},
        {"name": "99.7 fm"},
        {"name": "99.9 fm"},
        {"name": "@fm"},
        {"name": "@fm te conecta"},
        {"name": "aac"},
        {"name": "abc"},
        {"name": "acapulco"},
        {"name": "acir"},
        {"name": "acir online"},
        {"name": "acoustic"},
        {"name": "active rock"},
        {"name": "actualidad"},
        {"name": "adult"},
        {"name": "adult album alternative"},
        {"name": "adult alternative"},
        {"name": "adult contemporary"},
        {"name": "adult hits"},
        {"name": "adulta"},
        {"name": "african music"},
        {"name": "afro house"},
        {"name": "afrobeat"},
        {"name": "afrobeats"},
        {"name": "agriculture"},
        {"name": "aguascalientes"},
        {"name": "aguascalientes city"},
        {"name": "ai"},
        {"name": "album rock"},
        {"name": "alternative"},
        {"name": "alternative / indie"},
        {"name": "alternative pop"},
        {"name": "alternative rock"},
        {"name": "am"},
        {"name": "amapiano"},
        {"name": "ambient"},
        {"name": "ambient and relaxation music"},
        {"name": "american forces network"},
        {"name": "americana"},
        {"name": "amor"},
        {"name": "amor sólo música romántica"},
        {"name": "américa"},
        {"name": "anime"},
        {"name": "anthems"},
        {"name": "apm"},
        {"name": "aquí nomás"},
        {"name": "arabic"},
        {"name": "ard"},
        {"name": "argentina"},
        {"name": "arroba fm"},
        {"name": "arroba fm te conecta"},
        {"name": "art rock"},
        {"name": "arts"},
        {"name": "australian music"},
        {"name": "avant-garde"},
        {"name": "bachata"},
        {"name": "baja california"},
        {"name": "baja california sur"},
        {"name": "balada"},
        {"name": "balada en español"},
        {"name": "balada pop"},
        {"name": "balada romántica"},
        {"name": "baladas"},
        {"name": "baladas en español"},
        {"name": "baladas en inglés"},
        {"name": "ballads"},
        {"name": "banda"},
        {"name": "banda norteña"},
        {"name": "banda tradicional"},
        {"name": "baroque"},
        {"name": "bass"},
        {"name": "bbc"},
        {"name": "beats"},
        {"name": "bebop"},
        {"name": "best"},
        {"name": "bible"},
        {"name": "big band"},
        {"name": "black"},
        {"name": "black metal"},
        {"name": "bluegrass"},
        {"name": "blues"},
        {"name": "blues rock"},
        {"name": "boca del río"},
        {"name": "bolero"},
        {"name": "boleros"},
        {"name": "bollywood"},
        {"name": "bossa nova"},
        {"name": "boston"},
        {"name": "brasil"},
        {"name": "brazilian music"},
        {"name": "breakbeat"},
        {"name": "breaks"},
        {"name": "buenisiima"},
        {"name": "business"},
        {"name": "business news"},
        {"name": "cadena rasa"},
        {"name": "california"},
        {"name": "calm"},
        {"name": "campeche"},
        {"name": "campus radio"},
        {"name": "cancún"},
        {"name": "candela"},
        {"name": "catholic"},
        {"name": "catholic radio"},
        {"name": "catolica"},
        {"name": "católica"},
        {"name": "cdmx"},
        {"name": "celaya"},
        {"name": "celtic"},
        {"name": "chanson"},
        {"name": "chansons françaises"},
        {"name": "charts"},
        {"name": "chiapas"},
        {"name": "chicago"},
        {"name": "chihuahua"},
        {"name": "chihuahua city"},
        {"name": "children"},
        {"name": "chill"},
        {"name": "chillout"},
        {"name": "chillout+lounge"},
        {"name": "chiptune"},
        {"name": "chr"},
        {"name": "christian"},
        {"name": "christian contemporary"},
        {"name": "christian music"},
        {"name": "christian orthodox"},
        {"name": "christian praise&worship"},
        {"name": "christian talk"},
        {"name": "christian-gospel"},
        {"name": "christmas"},
        {"name": "christmas music"},
        {"name": "chrétien"},
        {"name": "ciudad de mexico"},
        {"name": "ciudad de méxico"},
        {"name": "ciudad juárez"},
        {"name": "ciudad mexico"},
        {"name": "ciudad obregón"},
        {"name": "clasicos"},
        {"name": "clasicos en ingles"},
        {"name": "classic"},
        {"name": "classic country"},
        {"name": "classic hip hop"},
        {"name": "classic hits"},
        {"name": "classic hits 60s 70a 80s"},
        {"name": "classic jazz"},
        {"name": "classic rock"},
        {"name": "classic rock oldies"},
        {"name": "classical"},
        {"name": "classical music"},
        {"name": "classical piano"},
        {"name": "classics"},
        {"name": "club"},
        {"name": "club dance"},
        {"name": "club dance electronic house trance"},
        {"name": "club house"},
        {"name": "clubbing"},
        {"name": "clásicos"},
        {"name": "clásicos en español"},
        {"name": "clásicos en español e inglés"},
        {"name": "clásicos en inglés"},
        {"name": "coahuila"},
        {"name": "college"},
        {"name": "college radio"},
        {"name": "combo"},
        {"name": "comedy"},
        {"name": "commercial"},
        {"name": "commercial-free"},
        {"name": "community"},
        {"name": "community radio"},
        {"name": "comunitaria"},
        {"name": "concesión pública"},
        {"name": "concesión social"},
        {"name": "conservative talk"},
        {"name": "contemporary"},
        {"name": "contemporary christian"},
        {"name": "contemporary hit radio"},
        {"name": "contemporary hits"},
        {"name": "contemporary hits radio"},
        {"name": "cool jazz"},
        {"name": "country"},
        {"name": "country music"},
        {"name": "country rock"},
        {"name": "cristiana"},
        {"name": "crooners"},
        {"name": "crossover"},
        {"name": "cuernavaca"},
        {"name": "culiacán"},
        {"name": "cultura"},
        {"name": "cultural"},
        {"name": "cultural news"},
        {"name": "culture"},
        {"name": "cumbia"},
        {"name": "cumbias"},
        {"name": "current affairs"},
        {"name": "córdoba"},
        {"name": "dab+"},
        {"name": "dance"},
        {"name": "dance music"},
        {"name": "dance pop"},
        {"name": "dancehall"},
        {"name": "dangdut"},
        {"name": "darkwave"},
        {"name": "death metal"},
        {"name": "debates y deportes"},
        {"name": "decades"},
        {"name": "deep"},
        {"name": "deep house"},
        {"name": "deporte"},
        {"name": "deportes"},
        {"name": "deutsch"},
        {"name": "deutschrock"},
        {"name": "disco"},
        {"name": "disco funk"},
        {"name": "disco polo"},
        {"name": "discofox"},
        {"name": "discography"},
        {"name": "disney"},
        {"name": "dj"},
        {"name": "dj mix"},
        {"name": "dj mixes"},
        {"name": "dj remix"},
        {"name": "dj sets"},
        {"name": "dnb"},
        {"name": "downtempo"},
        {"name": "drama"},
        {"name": "drgnu"},
        {"name": "drone"},
        {"name": "drum & bass"},
        {"name": "drum 'n' bass"},
        {"name": "drum and bass"},
        {"name": "dub"},
        {"name": "dubstep"},
        {"name": "durango"},
        {"name": "dutch"},
        {"name": "easy"},
        {"name": "easy listening"},
        {"name": "ebm"},
        {"name": "ecclesia"},
        {"name": "eclectic"},
        {"name": "eclectic programming"},
        {"name": "eclética"},
        {"name": "economics"},
        {"name": "edm"},
        {"name": "education"},
        {"name": "educational"},
        {"name": "el heraldo radio"},
        {"name": "el paso"},
        {"name": "electro"},
        {"name": "electro house"},
        {"name": "electronic"},
        {"name": "electronic dance music"},
        {"name": "electronic music"},
        {"name": "electronica"},
        {"name": "electropop"},
        {"name": "en todas partes"},
        {"name": "england"},
        {"name": "english"},
        {"name": "entertainment"},
        {"name": "entretenimiento"},
        {"name": "entrevistas"},
        {"name": "ert"},
        {"name": "español"},
        {"name": "espiritual"},
        {"name": "esportes"},
        {"name": "estación"},
        {"name": "estado de méxico"},
        {"name": "ethnic"},
        {"name": "etnic"},
        {"name": "etno"},
        {"name": "euro disco"},
        {"name": "eurodance"},
        {"name": "europe"},
        {"name": "evangelio"},
        {"name": "evergreens"},
        {"name": "exa"},
        {"name": "exa fm"},
        {"name": "exclusive"},
        {"name": "experimental"},
        {"name": "familia"},
        {"name": "family"},
        {"name": "features"},
        {"name": "film"},
        {"name": "film music"},
        {"name": "flashback"},
        {"name": "fm"},
        {"name": "fm globo"},
        {"name": "folclor"},
        {"name": "folclore"},
        {"name": "folk"},
        {"name": "folk music"},
        {"name": "folk rock"},
        {"name": "folklore"},
        {"name": "football"},
        {"name": "free"},
        {"name": "free jazz"},
        {"name": "free radio"},
        {"name": "freeform"},
        {"name": "freies radio"},
        {"name": "french"},
        {"name": "french music"},
        {"name": "fresh"},
        {"name": "full service"},
        {"name": "funk"},
        {"name": "funky"},
        {"name": "funky house"},
        {"name": "fusion"},
        {"name": "garage"},
        {"name": "gdl"},
        {"name": "geheimezender"},
        {"name": "general"},
        {"name": "german"},
        {"name": "glam rock"},
        {"name": "global"},
        {"name": "globalmedia"},
        {"name": "globo"},
        {"name": "gold"},
        {"name": "golden oldies"},
        {"name": "goldies"},
        {"name": "gospel"},
        {"name": "gospel music"},
        {"name": "gothic"},
        {"name": "government"},
        {"name": "greatest hits"},
        {"name": "greek"},
        {"name": "greek folk"},
        {"name": "greek folk music"},
        {"name": "greek music"},
        {"name": "greek pop"},
        {"name": "greek traditional"},
        {"name": "groove"},
        {"name": "grunge"},
        {"name": "grupera"},
        {"name": "gruperas del recuerdo"},
        {"name": "grupero"},
        {"name": "grupo acir"},
        {"name": "grupo as"},
        {"name": "grupo audiorama comunicaciones"},
        {"name": "grupo fórmula"},
        {"name": "grupo pazos"},
        {"name": "grupo promomedios"},
        {"name": "grupo radio alegría"},
        {"name": "grupo radio cañón"},
        {"name": "grupo radio centro"},
        {"name": "grupo radio digital"},
        {"name": "grupo radiofónico zer"},
        {"name": "grupo radiosa"},
        {"name": "grupo siete"},
        {"name": "grupo zer"},
        {"name": "guadalajara"},
        {"name": "guanajuato"},
        {"name": "guerrero"},
        {"name": "guitar"},
        {"name": "gómez palacio"},
        {"name": "hablada"},
        {"name": "handsup"},
        {"name": "hard rock"},
        {"name": "hard techno"},
        {"name": "hardcore"},
        {"name": "hardstyle"},
        {"name": "hd"},
        {"name": "health"},
        {"name": "heavy metal"},
        {"name": "heavy rock"},
        {"name": "heraldo media group"},
        {"name": "hermosillo"},
        {"name": "hindi"},
        {"name": "hip hop"},
        {"name": "hip-hop"},
        {"name": "hiphop"},
        {"name": "hits"},
        {"name": "hits 70's"},
        {"name": "holiday"},
        {"name": "hot ac"},
        {"name": "hot adult contemporary"},
        {"name": "hot hits"},
        {"name": "house"},
        {"name": "https"},
        {"name": "humour"},
        {"name": "ibiza"},
        {"name": "idm"},
        {"name": "iheart"},
        {"name": "iheart radio"},
        {"name": "independent"},
        {"name": "india"},
        {"name": "indie"},
        {"name": "indie music"},
        {"name": "indie pop"},
        {"name": "indie rock"},
        {"name": "indigenous"},
        {"name": "industrial"},
        {"name": "info"},
        {"name": "información"},
        {"name": "information"},
        {"name": "informativa"},
        {"name": "instrumental"},
        {"name": "instrumental music"},
        {"name": "international"},
        {"name": "international news"},
        {"name": "internet"},
        {"name": "internet radio"},
        {"name": "internet station"},
        {"name": "iptv"},
        {"name": "islam"},
        {"name": "islamic"},
        {"name": "italian"},
        {"name": "italian pop"},
        {"name": "italo disco"},
        {"name": "j-pop"},
        {"name": "jalisco"},
        {"name": "japanese"},
        {"name": "jazz"},
        {"name": "jazz fusion"},
        {"name": "jesus"},
        {"name": "jovem"},
        {"name": "jpop"},
        {"name": "jungle"},
        {"name": "juvenil"},
        {"name": "k-pop"},
        {"name": "kids"},
        {"name": "klassik"},
        {"name": "kpop"},
        {"name": "la bestia grupera"},
        {"name": "la comadre"},
        {"name": "la estación exacta"},
        {"name": "la estación naranja"},
        {"name": "la hora de luis miguel"},
        {"name": "la ke buena"},
        {"name": "la lupe"},
        {"name": "la mejor"},
        {"name": "la mejor aquí nomás"},
        {"name": "la mejor fm"},
        {"name": "la nueva candela"},
        {"name": "la poderosa"},
        {"name": "latin"},
        {"name": "latin music"},
        {"name": "latin pop"},
        {"name": "latina"},
        {"name": "latino"},
        {"name": "latino américa"},
        {"name": "latino urbano"},
        {"name": "latinoamerica"},
        {"name": "latinoamérica"},
        {"name": "león"},
        {"name": "lifestyle"},
        {"name": "literature"},
        {"name": "live"},
        {"name": "live concert"},
        {"name": "live sports"},
        {"name": "livestream"},
        {"name": "lo-fi"},
        {"name": "local"},
        {"name": "local information"},
        {"name": "local music"},
        {"name": "local news"},
        {"name": "local programming"},
        {"name": "local radio"},
        {"name": "local talk"},
        {"name": "lofi"},
        {"name": "london"},
        {"name": "los angeles"},
        {"name": "los mochis"},
        {"name": "los40"},
        {"name": "lounge"},
        {"name": "lounge music"},
        {"name": "love"},
        {"name": "love songs"},
        {"name": "lovesongs"},
        {"name": "luna de amor"},
        {"name": "m3u8"},
        {"name": "mainstream"},
        {"name": "mainstream rock"},
        {"name": "manele"},
        {"name": "mariachi"},
        {"name": "mashup"},
        {"name": "match"},
        {"name": "mazatlán"},
        {"name": "mediaset"},
        {"name": "medieval"},
        {"name": "meditation"},
        {"name": "mensajes cristianos"},
        {"name": "merengue"},
        {"name": "metal"},
        {"name": "metalcore"},
        {"name": "mex"},
        {"name": "mexicali"},
        {"name": "mexican music"},
        {"name": "mexico"},
        {"name": "mexico city"},
        {"name": "michoacán"},
        {"name": "minimal"},
        {"name": "minimal techno"},
        {"name": "misc"},
        {"name": "miscellaneous"},
        {"name": "mix"},
        {"name": "mix fm"},
        {"name": "mixed"},
        {"name": "modern"},
        {"name": "modern rock"},
        {"name": "moi merino"},
        {"name": "monterrey"},
        {"name": "morelia"},
        {"name": "morelos"},
        {"name": "motown"},
        {"name": "movie"},
        {"name": "movies"},
        {"name": "mp3"},
        {"name": "mpb"},
        {"name": "mrcrosby"},
        {"name": "mty"},
        {"name": "multicultural"},
        {"name": "multilingual"},
        {"name": "multimedios"},
        {"name": "multimedios radio"},
        {"name": "music"},
        {"name": "music only"},
        {"name": "musica"},
        {"name": "musica cristiana"},
        {"name": "musica italiana"},
        {"name": "musica latina"},
        {"name": "musica latinoamericana"},
        {"name": "musica mexicana"},
        {"name": "musica popular"},
        {"name": "musica regional"},
        {"name": "musica regional mexicana"},
        {"name": "musica romantica"},
        {"name": "musica tradicional mexicana"},
        {"name": "musical"},
        {"name": "musik"},
        {"name": "musique"},
        {"name": "mvs"},
        {"name": "mvs noticias"},
        {"name": "mvs radio"},
        {"name": "mx"},
        {"name": "mérida"},
        {"name": "méxico"},
        {"name": "música"},
        {"name": "música actual"},
        {"name": "música del recuerdo"},
        {"name": "música en español"},
        {"name": "música en español e inglés"},
        {"name": "música en inglés"},
        {"name": "música latina"},
        {"name": "música mexicana"},
        {"name": "música pop"},
        {"name": "música popular mexicana"},
        {"name": "música regional"},
        {"name": "música regional mexicana"},
        {"name": "música religiosa"},
        {"name": "música romántica"},
        {"name": "música tradicional mexicana"},
        {"name": "música tropical"},
        {"name": "música urbana"},
        {"name": "música variada"},
        {"name": "música y noticias"},
        {"name": "nachrichten"},
        {"name": "nacional"},
        {"name": "narodna"},
        {"name": "national"},
        {"name": "nature"},
        {"name": "nayarit"},
        {"name": "nederlandstalig"},
        {"name": "new age"},
        {"name": "new classics"},
        {"name": "new country"},
        {"name": "new format rebranding"},
        {"name": "new music"},
        {"name": "new wave"},
        {"name": "new york city"},
        {"name": "news"},
        {"name": "news talk"},
        {"name": "news talk music"},
        {"name": "nizhniy novgorod"},
        {"name": "no ads"},
        {"name": "non-commercial"},
        {"name": "non-profit"},
        {"name": "non-stop"},
        {"name": "non-stop music"},
        {"name": "norteamérica"},
        {"name": "norteña"},
        {"name": "norteño"},
        {"name": "nostalgia"},
        {"name": "noticias"},
        {"name": "noticias cortas"},
        {"name": "noticias en español"},
        {"name": "noticias locales"},
        {"name": "noticias nacionales e internacionales"},
        {"name": "noticias opinion"},
        {"name": "noticias regionales"},
        {"name": "noticias y comentarios"},
        {"name": "noticias y deportes"},
        {"name": "noticias y música"},
        {"name": "noticieros"},
        {"name": "notícias"},
        {"name": "npr"},
        {"name": "nrm comunicaciones"},
        {"name": "ntr medios de comunicación"},
        {"name": "nu disco"},
        {"name": "nu metal"},
        {"name": "nu-jazz"},
        {"name": "nuevo león"},
        {"name": "oaxaca"},
        {"name": "old school"},
        {"name": "old time radio"},
        {"name": "oldies"},
        {"name": "oldies 50's/60's"},
        {"name": "oldschool"},
        {"name": "online"},
        {"name": "online only"},
        {"name": "online radio"},
        {"name": "only music"},
        {"name": "only the golden classics"},
        {"name": "opera"},
        {"name": "opm"},
        {"name": "orchestral"},
        {"name": "orf"},
        {"name": "orthodox"},
        {"name": "orthodox christian"},
        {"name": "orthodoxy"},
        {"name": "other"},
        {"name": "otr"},
        {"name": "paradise"},
        {"name": "party"},
        {"name": "party hits"},
        {"name": "partymix"},
        {"name": "petrecere"},
        {"name": "phonk"},
        {"name": "piano"},
        {"name": "piano jazz"},
        {"name": "piedras negras"},
        {"name": "piraten"},
        {"name": "piratenhits"},
        {"name": "podcast"},
        {"name": "police scanner"},
        {"name": "polish"},
        {"name": "political talk"},
        {"name": "politics"},
        {"name": "ponte exa"},
        {"name": "pop"},
        {"name": "pop clásico"},
        {"name": "pop dance"},
        {"name": "pop en español"},
        {"name": "pop en español e inglés"},
        {"name": "pop en ingles"},
        {"name": "pop en inglés"},
        {"name": "pop latino"},
        {"name": "pop music"},
        {"name": "pop rock"},
        {"name": "pop-rock"},
        {"name": "popular"},
        {"name": "popular music"},
        {"name": "populară"},
        {"name": "post-punk"},
        {"name": "power metal"},
        {"name": "pri"},
        {"name": "programas en vivo"},
        {"name": "progressive"},
        {"name": "progressive house"},
        {"name": "progressive rock"},
        {"name": "progressive trance"},
        {"name": "psychedelic"},
        {"name": "psychedelic rock"},
        {"name": "psytrance"},
        {"name": "public"},
        {"name": "public radio"},
        {"name": "public service"},
        {"name": "puebla"},
        {"name": "puebla city"},
        {"name": "puerto vallarta"},
        {"name": "punk"},
        {"name": "punk rock"},
        {"name": "pública"},
        {"name": "queen"},
        {"name": "querétaro"},
        {"name": "querétaro city"},
        {"name": "quintana roo"},
        {"name": "quran"},
        {"name": "r&b"},
        {"name": "r&b/urban"},
        {"name": "r'n'b"},
        {"name": "r.sa"},
        {"name": "radcap"},
        {"name": "radio"},
        {"name": "radio caprice"},
        {"name": "radio communautaire"},
        {"name": "radio comunitaria"},
        {"name": "radio cristiana"},
        {"name": "radio disney"},
        {"name": "radio france"},
        {"name": "radio fórmula"},
        {"name": "radio fórmula primera cadena"},
        {"name": "radio hablada"},
        {"name": "radio local"},
        {"name": "radio online"},
        {"name": "radio publique"},
        {"name": "radio pública"},
        {"name": "radio reading service"},
        {"name": "radio sa"},
        {"name": "radio universal"},
        {"name": "radio universidad"},
        {"name": "radio universitaria"},
        {"name": "radiorama"},
        {"name": "radiópolis"},
        {"name": "ranchera"},
        {"name": "rancheras"},
        {"name": "rap"},
        {"name": "rap hiphop rnb"},
        {"name": "rare groove"},
        {"name": "rave"},
        {"name": "reggae"},
        {"name": "reggaeton"},
        {"name": "reggaetón"},
        {"name": "regional"},
        {"name": "regional mexican"},
        {"name": "regional mexicana"},
        {"name": "regional music"},
        {"name": "regional radio"},
        {"name": "relax"},
        {"name": "relaxation"},
        {"name": "relaxation music"},
        {"name": "relaxing"},
        {"name": "religion"},
        {"name": "religios"},
        {"name": "religiosa"},
        {"name": "religious"},
        {"name": "religión"},
        {"name": "remix"},
        {"name": "remixes"},
        {"name": "retro"},
        {"name": "retro hits"},
        {"name": "retro music"},
        {"name": "rhythm and blues"},
        {"name": "rnb"},
        {"name": "rock"},
        {"name": "rock & roll"},
        {"name": "rock 'n' roll"},
        {"name": "rock classics"},
        {"name": "rock en español"},
        {"name": "rock en inglés"},
        {"name": "rock music"},
        {"name": "rock n roll"},
        {"name": "rock'n'roll"},
        {"name": "rockabilly"},
        {"name": "rogers media"},
        {"name": "roma"},
        {"name": "romance"},
        {"name": "romanian"},
        {"name": "romantic"},
        {"name": "romantic music"},
        {"name": "romantica"},
        {"name": "romántica"},
        {"name": "románticas"},
        {"name": "roots"},
        {"name": "rtbf"},
        {"name": "russian"},
        {"name": "russian hits"},
        {"name": "russian rock"},
        {"name": "réunion"},
        {"name": "salsa"},
        {"name": "samba"},
        {"name": "san diego"},
        {"name": "san luis potosí"},
        {"name": "san luis potosí city"},
        {"name": "scanner"},
        {"name": "schlager"},
        {"name": "sertaneja"},
        {"name": "sertanejo"},
        {"name": "sertanejo raiz"},
        {"name": "servicio social"},
        {"name": "sierreño"},
        {"name": "sinaloa"},
        {"name": "singer-songwriter"},
        {"name": "ska"},
        {"name": "sleep"},
        {"name": "slow"},
        {"name": "slp"},
        {"name": "smooth"},
        {"name": "smooth jazz"},
        {"name": "smooth lounge"},
        {"name": "soca"},
        {"name": "soccer"},
        {"name": "social"},
        {"name": "soft"},
        {"name": "soft adult contemporary"},
        {"name": "soft music"},
        {"name": "soft pop"},
        {"name": "soft rock"},
        {"name": "sonora"},
        {"name": "soul"},
        {"name": "soulful house"},
        {"name": "soundtrack"},
        {"name": "soundtracks"},
        {"name": "southern rock"},
        {"name": "space"},
        {"name": "spanish"},
        {"name": "spanish adult hits"},
        {"name": "spanish contemporary hits"},
        {"name": "spiritual"},
        {"name": "spoken word"},
        {"name": "sport"},
        {"name": "sports"},
        {"name": "sports news"},
        {"name": "sports talk"},
        {"name": "srg ssr"},
        {"name": "star group"},
        {"name": "star radio"},
        {"name": "state college"},
        {"name": "storytelling"},
        {"name": "student"},
        {"name": "student radio"},
        {"name": "sureste"},
        {"name": "surf"},
        {"name": "sveriges radio"},
        {"name": "swing"},
        {"name": "synthpop"},
        {"name": "synthwave"},
        {"name": "sólo música romántica"},
        {"name": "tabasco"},
        {"name": "talk"},
        {"name": "talk & speech"},
        {"name": "talk radio"},
        {"name": "talk show"},
        {"name": "talks"},
        {"name": "tamaulipas"},
        {"name": "tamil"},
        {"name": "tamil music"},
        {"name": "tango"},
        {"name": "te conecta"},
        {"name": "tech house"},
        {"name": "techno"},
        {"name": "technology"},
        {"name": "tepic"},
        {"name": "texas"},
        {"name": "the beatles"},
        {"name": "the best of 80's"},
        {"name": "thrash metal"},
        {"name": "tijuana"},
        {"name": "toluca"},
        {"name": "top"},
        {"name": "top 100"},
        {"name": "top 40"},
        {"name": "top 40 hits"},
        {"name": "top charts"},
        {"name": "top hits"},
        {"name": "top100"},
        {"name": "top40"},
        {"name": "toronto"},
        {"name": "torreón"},
        {"name": "traditional"},
        {"name": "traditional mexican music"},
        {"name": "traffic"},
        {"name": "traffic information"},
        {"name": "traffic radio broadcast"},
        {"name": "trance"},
        {"name": "trap"},
        {"name": "trip-hop"},
        {"name": "tropical"},
        {"name": "tropical music"},
        {"name": "turkish music"},
        {"name": "tv"},
        {"name": "uk"},
        {"name": "uk garage"},
        {"name": "underground"},
        {"name": "united kingdom"},
        {"name": "universidad"},
        {"name": "universitaria"},
        {"name": "university"},
        {"name": "university radio"},
        {"name": "urban"},
        {"name": "urban adult contemporary"},
        {"name": "urban contemporary"},
        {"name": "urbano"},
        {"name": "usa"},
        {"name": "valle de méxico"},
        {"name": "vallenato"},
        {"name": "vaporwave"},
        {"name": "variada"},
        {"name": "variado"},
        {"name": "varied"},
        {"name": "variedad"},
        {"name": "variety"},
        {"name": "variety hits"},
        {"name": "various"},
        {"name": "various music"},
        {"name": "veracruz"},
        {"name": "veracruz city"},
        {"name": "video game music"},
        {"name": "videogame music"},
        {"name": "villahermosa"},
        {"name": "vintage"},
        {"name": "vocal"},
        {"name": "vocal jazz"},
        {"name": "volksmusik"},
        {"name": "vox"},
        {"name": "vox fm"},
        {"name": "vrt"},
        {"name": "w radio"},
        {"name": "walm"},
        {"name": "waynesboro"},
        {"name": "weather"},
        {"name": "webradio"},
        {"name": "weihnachten"},
        {"name": "workout"},
        {"name": "world"},
        {"name": "world middle east"},
        {"name": "world music"},
        {"name": "world news"},
        {"name": "worship"},
        {"name": "xalapa"},
        {"name": "yoga"},
        {"name": "youth"},
        {"name": "yucatán"},
        {"name": "zabavna"},
        {"name": "zacatecas"},
        {"name": "éxitos"},
        {"name": "ορθοδοξία"},
        {"name": "лëгкая музыка"},
        {"name": "поп-музыка"},
        {"name": "ретро"},
        {"name": "рок"},
        {"name": "танцевальная"},
        {"name": "электронная"},
      ];
    }
    current = raw.firstWhereOrNull((item) => item['name'] == widget.currentTag);
    search(query.text.trim());
  }

  void search(String query) {
    if (query.isEmpty) {
      searchTags = raw;
    } else {
      searchTags = raw
          .where(
            (item) => item['name'].toLowerCase().contains(query.toLowerCase()),
          )
          .toList();
    }
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      child: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          children: [
            TextFieldBox(
              onChanged: search,
              autofocus: true,
              controller: query,
              labelText: S.of(context).tags,
              maxLines: 1,
            ),
            if (current != null) ...[Text(current!['name']), Divider()],
            Flexible(
              child: raw.isEmpty
                  ? Loading()
                  : ListView.builder(
                      itemCount: searchTags.length,
                      itemBuilder: (BuildContext context, int index) {
                        final tag = searchTags[index];
                        return InkWell(
                          child: Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: Column(
                              crossAxisAlignment: .start,
                              spacing: 2,
                              children: [
                                Text(tag['name']),
                                if (tag['stationCount'] != null)
                                  Text(
                                    "${S.of(context).stationCount} : ${tag['stationCount'].toString()}",
                                    style: TextStyle(
                                      color: Theme.of(context)
                                          .colorScheme
                                          .onSurfaceVariant
                                          .withValues(alpha: 0.7),
                                      fontSize: 13,
                                    ),
                                  ),
                              ],
                            ),
                          ),
                          onTap: () {
                            Navigator.pop(context, searchTags[index]['name']);
                          },
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }
}
