import 'package:flutter/material.dart';
import 'package:sound_center/shared/widgets/text_field_box.dart';
import 'package:sound_center/shared/widgets/text_view.dart';

class TagListDialog extends StatefulWidget {
  const TagListDialog({super.key});

  @override
  State<TagListDialog> createState() => _TagListDialogState();
}

class _TagListDialogState extends State<TagListDialog> {
  List<Map<String, dynamic>> raw = [
    {"name": "pop", "stationcount": 5816},
    {"name": "music", "stationcount": 4899},
    {"name": "rock", "stationcount": 3026},
    {"name": "news", "stationcount": 2821},
    {"name": "radio", "stationcount": 2168},
    {"name": "entretenimiento", "stationcount": 2067},
    {"name": "estación", "stationcount": 2041},
    {"name": "méxico", "stationcount": 1909},
    {"name": "norteamérica", "stationcount": 1819},
    {"name": "fm", "stationcount": 1729},
    {"name": "moi merino", "stationcount": 1703},
    {"name": "música", "stationcount": 1645},
    {"name": "latinoamérica", "stationcount": 1632},
    {"name": "español", "stationcount": 1597},
    {"name": "classical", "stationcount": 1578},
    {"name": "dance", "stationcount": 1509},
    {"name": "hits", "stationcount": 1470},
    {"name": "talk", "stationcount": 1464},
    {"name": "américa", "stationcount": 1382},
    {"name": "oldies", "stationcount": 1344},
    {"name": "pop music", "stationcount": 1237},
    {"name": "80s", "stationcount": 1196},
    {"name": "jazz", "stationcount": 1161},
    {"name": "música en español", "stationcount": 990},
    {"name": "top 40", "stationcount": 984},
    {"name": "90s", "stationcount": 956},
    {"name": "electronic", "stationcount": 948},
    {"name": "public radio", "stationcount": 940},
    {"name": "christian", "stationcount": 924},
    {"name": "adult contemporary", "stationcount": 903},
    {"name": "pop rock", "stationcount": 891},
    {"name": "classic rock", "stationcount": 881},
    {"name": "classic hits", "stationcount": 871},
    {"name": "community radio", "stationcount": 818},
    {"name": "música pop", "stationcount": 773},
    {"name": "local news", "stationcount": 760},
    {"name": "house", "stationcount": 721},
    {"name": "country", "stationcount": 677},
    {"name": "regional mexican", "stationcount": 673},
    {"name": "alternative", "stationcount": 672},
    {"name": "regional", "stationcount": 634},
    {"name": "regional mexicana", "stationcount": 625},
    {"name": "música popular mexicana", "stationcount": 599},
    {"name": "local radio", "stationcount": 595},
    {"name": "folk", "stationcount": 587},
    {"name": "noticias", "stationcount": 578},
    {"name": "70s", "stationcount": 564},
    {"name": "música regional", "stationcount": 551},
    {"name": "information", "stationcount": 550},
    {"name": "mexican music", "stationcount": 516},
    {"name": "variety", "stationcount": 486},
    {"name": "grupera", "stationcount": 475},
    {"name": "música regional mexicana", "stationcount": 474},
    {"name": "música mexicana", "stationcount": 471},
    {"name": "regional music", "stationcount": 467},
    {"name": "mexico", "stationcount": 447},
    {"name": "juvenil", "stationcount": 447},
    {"name": "regional radio", "stationcount": 441},
    {"name": "news talk", "stationcount": 435},
    {"name": "metal", "stationcount": 433},
    {"name": "soul", "stationcount": 424},
    {"name": "música en español e inglés", "stationcount": 418},
    {"name": "chillout", "stationcount": 417},
    {"name": "indie", "stationcount": 412},
    {"name": "pop en español e inglés", "stationcount": 405},
    {"name": "easy listening", "stationcount": 397},
    {"name": "música variada", "stationcount": 397},
    {"name": "música y noticias", "stationcount": 394},
    {"name": "traditional mexican music", "stationcount": 389},
    {"name": "sports", "stationcount": 386},
    {"name": "banda", "stationcount": 382},
    {"name": "techno", "stationcount": 379},
    {"name": "retro", "stationcount": 373},
    {"name": "música del recuerdo", "stationcount": 364},
    {"name": "ambient", "stationcount": 361},
    {"name": "top hits", "stationcount": 359},
    {"name": "radio hablada", "stationcount": 358},
    {"name": "2000s", "stationcount": 346},
    {"name": "ciudad de méxico", "stationcount": 345},
    {"name": "disco", "stationcount": 343},
    {"name": "culture", "stationcount": 340},
    {"name": "religious", "stationcount": 340},
    {"name": "entertainment", "stationcount": 339},
    {"name": "gospel", "stationcount": 333},
    {"name": "lounge", "stationcount": 327},
    {"name": "alternative rock", "stationcount": 327},
    {"name": "full service", "stationcount": 324},
    {"name": "grupero", "stationcount": 319},
    {"name": "top40", "stationcount": 316},
    {"name": "valle de méxico", "stationcount": 316},
    {"name": "am", "stationcount": 315},
    {"name": "blues", "stationcount": 314},
    {"name": "mexico city", "stationcount": 312},
    {"name": "funk", "stationcount": 311},
    {"name": "mex", "stationcount": 307},
    {"name": "mx", "stationcount": 306},
    {"name": "local", "stationcount": 306},
    {"name": "música tradicional mexicana", "stationcount": 305},
    {"name": "programas en vivo", "stationcount": 304},
    {"name": "rap", "stationcount": 303},
    {"name": "musica", "stationcount": 298},
    {"name": "greek", "stationcount": 294},
    {"name": "commercial", "stationcount": 293},
    {"name": "noticias locales", "stationcount": 290},
    {"name": "cdmx", "stationcount": 289},
    {"name": "edm", "stationcount": 286},
    {"name": "80's", "stationcount": 285},
    {"name": "trance", "stationcount": 285},
    {"name": "música en inglés", "stationcount": 283},
    {"name": "hiphop", "stationcount": 282},
    {"name": "salsa", "stationcount": 275},
    {"name": "latin pop", "stationcount": 272},
    {"name": "clásicos", "stationcount": 270},
    {"name": "latino", "stationcount": 269},
    {"name": "misc", "stationcount": 266},
    {"name": "electro", "stationcount": 265},
    {"name": "baladas en español", "stationcount": 264},
    {"name": "world music", "stationcount": 263},
    {"name": "smooth jazz", "stationcount": 258},
    {"name": "60s", "stationcount": 255},
    {"name": "contemporary hits", "stationcount": 255},
    {"name": "npr", "stationcount": 254},
    {"name": "tropical", "stationcount": 249},
    {"name": "eclectic", "stationcount": 247},
    {"name": "hot adult contemporary", "stationcount": 245},
    {"name": "mvs radio", "stationcount": 242},
    {"name": "reggae", "stationcount": 241},
    {"name": "hard rock", "stationcount": 240},
    {"name": "mainstream", "stationcount": 238},
    {"name": "radiópolis", "stationcount": 238},
    {"name": "cumbia", "stationcount": 237},
    {"name": "pop en inglés", "stationcount": 236},
    {"name": "mvs", "stationcount": 233},
    {"name": "university radio", "stationcount": 233},
    {"name": "deep house", "stationcount": 231},
    {"name": "popular", "stationcount": 229},
    {"name": "noticias en español", "stationcount": 226},
    {"name": "noticias y comentarios", "stationcount": 223},
    {"name": "sureste", "stationcount": 222},
    {"name": "schlager", "stationcount": 222},
    {"name": "relax", "stationcount": 220},
    {"name": "hip-hop", "stationcount": 220},
    {"name": "college radio", "stationcount": 215},
    {"name": "reggaeton", "stationcount": 211},
    {"name": "talk & speech", "stationcount": 211},
    {"name": "rnb", "stationcount": 209},
    {"name": "local music", "stationcount": 209},
    {"name": "contemporary hits radio", "stationcount": 206},
    {"name": "top charts", "stationcount": 200},
    {"name": "pop en español", "stationcount": 198},
    {"name": "various", "stationcount": 197},
    {"name": "1980s", "stationcount": 196},
    {"name": "90's", "stationcount": 193},
    {"name": "baladas", "stationcount": 193},
    {"name": "charts", "stationcount": 191},
    {"name": "instrumental", "stationcount": 189},
    {"name": "sport", "stationcount": 187},
    {"name": "religion", "stationcount": 186},
    {"name": "christmas music", "stationcount": 184},
    {"name": "pop dance", "stationcount": 183},
    {"name": "heavy metal", "stationcount": 182},
    {"name": "international", "stationcount": 181},
    {"name": "community", "stationcount": 179},
    {"name": "noticias nacionales e internacionales", "stationcount": 179},
    {"name": "radiorama", "stationcount": 176},
    {"name": "hablada", "stationcount": 175},
    {"name": "electronica", "stationcount": 171},
    {"name": "00s", "stationcount": 170},
    {"name": "hip hop", "stationcount": 170},
    {"name": "balada pop", "stationcount": 169},
    {"name": "iheart radio", "stationcount": 169},
    {"name": "80er", "stationcount": 168},
    {"name": "iheart", "stationcount": 168},
    {"name": "classic", "stationcount": 167},
    {"name": "veracruz", "stationcount": 167},
    {"name": "soft rock", "stationcount": 166},
    {"name": "talk radio", "stationcount": 166},
    {"name": "clásicos en inglés", "stationcount": 166},
    {"name": "grupo acir", "stationcount": 164},
    {"name": "mix", "stationcount": 163},
    {"name": "chill", "stationcount": 162},
    {"name": "banda norteña", "stationcount": 162},
    {"name": "musica romantica", "stationcount": 162},
    {"name": "adult hits", "stationcount": 161},
    {"name": "r&b", "stationcount": 160},
    {"name": "balada en español", "stationcount": 159},
    {"name": "acir", "stationcount": 157},
    {"name": "top 100", "stationcount": 157},
    {"name": "norteño", "stationcount": 156},
    {"name": "punk", "stationcount": 155},
    {"name": "deportes", "stationcount": 155},
    {"name": "top", "stationcount": 153},
    {"name": "latin", "stationcount": 153},
    {"name": "classics", "stationcount": 150},
    {"name": "catholic", "stationcount": 147},
    {"name": "club", "stationcount": 146},
    {"name": "romantic", "stationcount": 146},
    {"name": "top 40 hits", "stationcount": 145},
    {"name": "поп-музыка", "stationcount": 145},
    {"name": "balada", "stationcount": 144},
    {"name": "vallenato", "stationcount": 144},
    {"name": "indie rock", "stationcount": 144},
    {"name": "radio caprice", "stationcount": 142},
    {"name": "urban", "stationcount": 141},
    {"name": "exa fm", "stationcount": 141},
    {"name": "eurodance", "stationcount": 141},
    {"name": "exa", "stationcount": 138},
    {"name": "online", "stationcount": 138},
    {"name": "ponte exa", "stationcount": 138},
    {"name": "progressive rock", "stationcount": 136},
    {"name": "2010s", "stationcount": 135},
    {"name": "musica regional mexicana", "stationcount": 135},
    {"name": "politics", "stationcount": 134},
    {"name": "greek music", "stationcount": 134},
    {"name": "la estación exacta", "stationcount": 134},
    {"name": "la estación naranja", "stationcount": 134},
    {"name": "1990s", "stationcount": 131},
    {"name": "party", "stationcount": 131},
    {"name": "latin music", "stationcount": 131},
    {"name": "experimental", "stationcount": 131},
    {"name": "classical music", "stationcount": 131},
    {"name": "radio online", "stationcount": 130},
    {"name": "traffic", "stationcount": 129},
    {"name": "musica latina", "stationcount": 128},
    {"name": "electronic dance music", "stationcount": 125},
    {"name": "jalisco", "stationcount": 124},
    {"name": "90er", "stationcount": 123},
    {"name": "cultural", "stationcount": 122},
    {"name": "love songs", "stationcount": 121},
    {"name": "online only", "stationcount": 121},
    {"name": "internet radio", "stationcount": 120},
    {"name": "sinaloa", "stationcount": 118},
    {"name": "non-commercial", "stationcount": 118},
    {"name": "combo", "stationcount": 117},
    {"name": "crossover", "stationcount": 116},
    {"name": "contemporary", "stationcount": 115},
    {"name": "balada romántica", "stationcount": 115},
    {"name": "new wave", "stationcount": 114},
    {"name": "musica regional", "stationcount": 114},
    {"name": "clásicos en español", "stationcount": 112},
    {"name": "1970s", "stationcount": 111},
    {"name": "sports news", "stationcount": 111},
    {"name": "ranchera", "stationcount": 110},
    {"name": "greek pop", "stationcount": 110},
    {"name": "romántica", "stationcount": 109},
    {"name": "downtempo", "stationcount": 108},
    {"name": "local information", "stationcount": 108},
    {"name": "70's", "stationcount": 107},
    {"name": "románticas", "stationcount": 107},
    {"name": "discography", "stationcount": 105},
    {"name": "pop clásico", "stationcount": 105},
    {"name": "música romántica", "stationcount": 105},
    {"name": "public", "stationcount": 103},
    {"name": "cristiana", "stationcount": 103},
    {"name": "bible", "stationcount": 102},
    {"name": "información", "stationcount": 102},
    {"name": "noticias y deportes", "stationcount": 102},
    {"name": "sonora", "stationcount": 101},
    {"name": "merengue", "stationcount": 101},
    {"name": "noticias y música", "stationcount": 101},
    {"name": "christmas", "stationcount": 100},
    {"name": "drum and bass", "stationcount": 100},
    {"name": "spanish contemporary hits", "stationcount": 100},
    {"name": "kids", "stationcount": 99},
    {"name": "chihuahua", "stationcount": 99},
    {"name": "tv", "stationcount": 98},
    {"name": "youth", "stationcount": 98},
    {"name": "social", "stationcount": 98},
    {"name": "norteña", "stationcount": 98},
    {"name": "informativa", "stationcount": 98},
    {"name": "mediaset", "stationcount": 97},
    {"name": "musica mexicana", "stationcount": 97},
    {"name": "grupo radio cañón", "stationcount": 97},
    {"name": "coahuila", "stationcount": 96},
    {"name": "miscellaneous", "stationcount": 96},
    {"name": "noticias cortas", "stationcount": 94},
    {"name": "monterrey", "stationcount": 92},
    {"name": "musica tradicional mexicana", "stationcount": 92},
    {"name": "manele", "stationcount": 91},
    {"name": "children", "stationcount": 91},
    {"name": "california", "stationcount": 91},
    {"name": "usa", "stationcount": 90},
    {"name": "radcap", "stationcount": 90},
    {"name": "guanajuato", "stationcount": 90},
    {"name": "nuevo león", "stationcount": 90},
    {"name": "radio pública", "stationcount": 90},
    {"name": "news talk music", "stationcount": 90},
    {"name": "ambient and relaxation music", "stationcount": 90},
    {"name": "70er", "stationcount": 89},
    {"name": "italian pop", "stationcount": 89},
    {"name": "comedy", "stationcount": 88},
    {"name": "w radio", "stationcount": 88},
    {"name": "musica latinoamericana", "stationcount": 88},
    {"name": "public service", "stationcount": 87},
    {"name": "radio comunitaria", "stationcount": 87},
    {"name": "smooth", "stationcount": 86},
    {"name": "tech house", "stationcount": 86},
    {"name": "aac", "stationcount": 85},
    {"name": "trap", "stationcount": 85},
    {"name": "relaxing", "stationcount": 85},
    {"name": "dance music", "stationcount": 85},
    {"name": "progressive", "stationcount": 85},
    {"name": "pública", "stationcount": 84},
    {"name": "música tropical", "stationcount": 84},
    {"name": "lifestyle", "stationcount": 83},
    {"name": "sports talk", "stationcount": 83},
    {"name": "old time radio", "stationcount": 83},
    {"name": "ntr medios de comunicación", "stationcount": 83},
    {"name": "local talk", "stationcount": 82},
    {"name": "dj", "stationcount": 81},
    {"name": "piano", "stationcount": 81},
    {"name": "mariachi", "stationcount": 81},
    {"name": "tropical music", "stationcount": 81},
    {"name": "grupo audiorama comunicaciones", "stationcount": 81},
    {"name": "hardcore", "stationcount": 80},
    {"name": "folk music", "stationcount": 80},
    {"name": "guadalajara", "stationcount": 80},
    {"name": "música urbana", "stationcount": 80},
    {"name": "decades", "stationcount": 79},
    {"name": "club dance", "stationcount": 79},
    {"name": "pop latino", "stationcount": 79},
    {"name": "live sports", "stationcount": 79},
    {"name": "en todas partes", "stationcount": 79},
    {"name": "romantic music", "stationcount": 78},
    {"name": "concesión social", "stationcount": 78},
    {"name": "los40", "stationcount": 77},
    {"name": "world", "stationcount": 77},
    {"name": "gothic", "stationcount": 77},
    {"name": "internet", "stationcount": 77},
    {"name": "christian contemporary", "stationcount": 77},
    {"name": "radio universitaria", "stationcount": 76},
    {"name": "university", "stationcount": 75},
    {"name": "waynesboro", "stationcount": 75},
    {"name": "abc", "stationcount": 74},
    {"name": "1960s", "stationcount": 74},
    {"name": "michoacán", "stationcount": 73},
    {"name": "african music", "stationcount": 73},
    {"name": "alternative / indie", "stationcount": 73},
    {"name": "50s", "stationcount": 72},
    {"name": "amor", "stationcount": 72},
    {"name": "russian", "stationcount": 72},
    {"name": "entrevistas", "stationcount": 72},
    {"name": "grupo radio centro", "stationcount": 72},
    {"name": "college", "stationcount": 71},
    {"name": "greek folk", "stationcount": 71},
    {"name": "country music", "stationcount": 71},
    {"name": "mpb", "stationcount": 70},
    {"name": "urbano", "stationcount": 70},
    {"name": "weather", "stationcount": 70},
    {"name": "petrecere", "stationcount": 70},
    {"name": "student radio", "stationcount": 70},
    {"name": "24/7", "stationcount": 69},
    {"name": "live", "stationcount": 69},
    {"name": "blues rock", "stationcount": 69},
    {"name": "retro hits", "stationcount": 69},
    {"name": "retro music", "stationcount": 69},
    {"name": "various music", "stationcount": 69},
    {"name": "aguascalientes", "stationcount": 69},
    {"name": "chillout+lounge", "stationcount": 69},
    {"name": "la mejor", "stationcount": 68},
    {"name": "hardstyle", "stationcount": 68},
    {"name": "world news", "stationcount": 68},
    {"name": "baja california", "stationcount": 68},
    {"name": "anime", "stationcount": 67},
    {"name": "new age", "stationcount": 67},
    {"name": "dj remix", "stationcount": 67},
    {"name": "noticias opinion", "stationcount": 67},
    {"name": "estado de méxico", "stationcount": 67},
    {"name": "love", "stationcount": 66},
    {"name": "dubstep", "stationcount": 66},
    {"name": "exclusive", "stationcount": 66},
    {"name": "punk rock", "stationcount": 66},
    {"name": "adult", "stationcount": 65},
    {"name": "freeform", "stationcount": 65},
    {"name": "arroba fm", "stationcount": 65},
    {"name": "bollywood", "stationcount": 65},
    {"name": "cadena rasa", "stationcount": 65},
    {"name": "@fm", "stationcount": 64},
    {"name": "swing", "stationcount": 64},
    {"name": "cultura", "stationcount": 64},
    {"name": "acir online", "stationcount": 64},
    {"name": "@fm te conecta", "stationcount": 64},
    {"name": "arroba fm te conecta", "stationcount": 64},
    {"name": "sertanejo", "stationcount": 63},
    {"name": "talk show", "stationcount": 63},
    {"name": "te conecta", "stationcount": 63},
    {"name": "soundtracks", "stationcount": 63},
    {"name": "classic country", "stationcount": 63},
    {"name": "san luis potosí", "stationcount": 63},
    {"name": "gdl", "stationcount": 62},
    {"name": "mp3", "stationcount": 62},
    {"name": "populară", "stationcount": 62},
    {"name": "relaxation", "stationcount": 62},
    {"name": "la mejor fm", "stationcount": 62},
    {"name": "christian music", "stationcount": 62},
    {"name": "the best of 80's", "stationcount": 62},
    {"name": "dub", "stationcount": 61},
    {"name": "rancheras", "stationcount": 61},
    {"name": "aquí nomás", "stationcount": 61},
    {"name": "current affairs", "stationcount": 61},
    {"name": "musica italiana", "stationcount": 61},
    {"name": "rock en español", "stationcount": 61},
    {"name": "urban contemporary", "stationcount": 61},
    {"name": "la mejor aquí nomás", "stationcount": 61},
    {"name": "otr", "stationcount": 60},
    {"name": "goldies", "stationcount": 60},
    {"name": "meditation", "stationcount": 60},
    {"name": "traditional", "stationcount": 60},
    {"name": "lounge music", "stationcount": 60},
    {"name": "música actual", "stationcount": 60},
    {"name": "free", "stationcount": 59},
    {"name": "grunge", "stationcount": 59},
    {"name": "puebla", "stationcount": 59},
    {"name": "noticieros", "stationcount": 59},
    {"name": "independent", "stationcount": 59},
    {"name": "banda tradicional", "stationcount": 59},
    {"name": "orthodox christian", "stationcount": 59},
    {"name": "traffic radio broadcast", "stationcount": 59},
    {"name": "opm", "stationcount": 58},
    {"name": "sierreño", "stationcount": 58},
    {"name": "pri", "stationcount": 57},
    {"name": "minimal", "stationcount": 57},
    {"name": "big band", "stationcount": 57},
    {"name": "afrobeats", "stationcount": 57},
    {"name": "industrial", "stationcount": 57},
    {"name": "educational", "stationcount": 57},
    {"name": "multicultural", "stationcount": 57},
    {"name": "groove", "stationcount": 56},
    {"name": "ballads", "stationcount": 56},
    {"name": "dj sets", "stationcount": 56},
    {"name": "dj mixes", "stationcount": 55},
    {"name": "radio local", "stationcount": 55},
    {"name": "electro house", "stationcount": 55},
    {"name": "ciudad de mexico", "stationcount": 55},
    {"name": "jpop", "stationcount": 54},
    {"name": "https", "stationcount": 54},
    {"name": "klassik", "stationcount": 54},
    {"name": "dance pop", "stationcount": 54},
    {"name": "dancehall", "stationcount": 54},
    {"name": "italo disco", "stationcount": 54},
    {"name": "americana", "stationcount": 53},
    {"name": "volksmusik", "stationcount": 53},
    {"name": "universitaria", "stationcount": 53},
    {"name": "singer-songwriter", "stationcount": 53},
    {"name": "ska", "stationcount": 52},
    {"name": "hot ac", "stationcount": 52},
    {"name": "islamic", "stationcount": 52},
    {"name": "features", "stationcount": 52},
    {"name": "la ke buena", "stationcount": 52},
    {"name": "brazilian music", "stationcount": 52},
    {"name": "multimedios radio", "stationcount": 52},
    {"name": "ard", "stationcount": 51},
    {"name": "bachata", "stationcount": 51},
    {"name": "eclética", "stationcount": 51},
    {"name": "economics", "stationcount": 51},
    {"name": "education", "stationcount": 51},
    {"name": "psychedelic", "stationcount": 51},
    {"name": "rock en inglés", "stationcount": 51},
    {"name": "local programming", "stationcount": 51},
    {"name": "soft adult contemporary", "stationcount": 51},
    {"name": "opera", "stationcount": 50},
    {"name": "1980's", "stationcount": 50},
    {"name": "2000er", "stationcount": 50},
    {"name": "indie pop", "stationcount": 50},
    {"name": "star group", "stationcount": 50},
    {"name": "golden oldies", "stationcount": 50},
    {"name": "radio fórmula", "stationcount": 50},
    {"name": "60er", "stationcount": 49},
    {"name": "texas", "stationcount": 49},
    {"name": "no ads", "stationcount": 49},
    {"name": "non-stop music", "stationcount": 49},
    {"name": "funky", "stationcount": 48},
    {"name": "italian", "stationcount": 48},
    {"name": "100.1 fm", "stationcount": 48},
    {"name": "evangelio", "stationcount": 48},
    {"name": "zacatecas", "stationcount": 48},
    {"name": "livestream", "stationcount": 48},
    {"name": "soundtrack", "stationcount": 48},
    {"name": "star radio", "stationcount": 48},
    {"name": "radio france", "stationcount": 48},
    {"name": "boca del río", "stationcount": 48},
    {"name": "grupo fórmula", "stationcount": 48},
    {"name": "progressive house", "stationcount": 48},
    {"name": "lofi", "stationcount": 47},
    {"name": "1950s", "stationcount": 47},
    {"name": "2020s", "stationcount": 47},
    {"name": "mixed", "stationcount": 47},
    {"name": "cumbias", "stationcount": 47},
    {"name": "deporte", "stationcount": 47},
    {"name": "indigenous", "stationcount": 47},
    {"name": "tamaulipas", "stationcount": 47},
    {"name": "ciudad mexico", "stationcount": 47},
    {"name": "political talk", "stationcount": 47},
    {"name": "radio universidad", "stationcount": 47},
    {"name": "adult album alternative", "stationcount": 47},
    {"name": "vrt", "stationcount": 46},
    {"name": "deep", "stationcount": 46},
    {"name": "durango", "stationcount": 46},
    {"name": "music only", "stationcount": 46},
    {"name": "drum & bass", "stationcount": 46},
    {"name": "piratenhits", "stationcount": 46},
    {"name": "underground", "stationcount": 46},
    {"name": "campus radio", "stationcount": 46},
    {"name": "soulful house", "stationcount": 46},
    {"name": "dnb", "stationcount": 45},
    {"name": "mty", "stationcount": 45},
    {"name": "europe", "stationcount": 45},
    {"name": "acoustic", "stationcount": 45},
    {"name": "guerrero", "stationcount": 45},
    {"name": "flashback", "stationcount": 45},
    {"name": "rap hiphop rnb", "stationcount": 45},
    {"name": "international news", "stationcount": 45},
    {"name": "hd", "stationcount": 44},
    {"name": "hindi", "stationcount": 44},
    {"name": "jungle", "stationcount": 44},
    {"name": "general", "stationcount": 44},
    {"name": "srg ssr", "stationcount": 44},
    {"name": "new music", "stationcount": 44},
    {"name": "nostalgia", "stationcount": 44},
    {"name": "veracruz city", "stationcount": 44},
    {"name": "electronic music", "stationcount": 44},
    {"name": "oldies 50's/60's", "stationcount": 44},
    {"name": "grupo radiofónico zer", "stationcount": 44},
    {"name": "clásicos en español e inglés", "stationcount": 44},
    {"name": "60's", "stationcount": 43},
    {"name": "black", "stationcount": 43},
    {"name": "90s y más", "stationcount": 43},
    {"name": "ретро", "stationcount": 43},
    {"name": "london", "stationcount": 42},
    {"name": "рок", "stationcount": 42},
    {"name": "pop-rock", "stationcount": 42},
    {"name": "synthpop", "stationcount": 42},
    {"name": "yucatán", "stationcount": 42},
    {"name": "romantica", "stationcount": 42},
    {"name": "variety hits", "stationcount": 42},
    {"name": "80s en español", "stationcount": 42},
    {"name": "aguascalientes city", "stationcount": 42},
    {"name": "amor sólo música romántica", "stationcount": 42},
    {"name": "mix fm", "stationcount": 41},
    {"name": "remixes", "stationcount": 41},
    {"name": "worship", "stationcount": 41},
    {"name": "club house", "stationcount": 41},
    {"name": "rock classics", "stationcount": 41},
    {"name": "australian music", "stationcount": 41},
    {"name": "concesión pública", "stationcount": 41},
    {"name": "sólo música romántica", "stationcount": 41},
    {"name": "león", "stationcount": 40},
    {"name": "98.5 fm", "stationcount": 40},
    {"name": "99.3 fm", "stationcount": 40},
    {"name": "romance", "stationcount": 40},
    {"name": "folklore", "stationcount": 40},
    {"name": "grupo zer", "stationcount": 40},
    {"name": "literature", "stationcount": 40},
    {"name": "club dance electronic house trance", "stationcount": 40},
    {"name": "ai", "stationcount": 39},
    {"name": "apm", "stationcount": 39},
    {"name": "slp", "stationcount": 39},
    {"name": "sleep", "stationcount": 39},
    {"name": "family", "stationcount": 39},
    {"name": "93.3 fm", "stationcount": 39},
    {"name": "chiapas", "stationcount": 39},
    {"name": "101.7 fm", "stationcount": 39},
    {"name": "mvs noticias", "stationcount": 39},
    {"name": "cultural news", "stationcount": 39},
    {"name": "christian-gospel", "stationcount": 39},
    {"name": "world middle east", "stationcount": 39},
    {"name": "debates y deportes", "stationcount": 39},
    {"name": "ebm", "stationcount": 38},
    {"name": "other", "stationcount": 38},
    {"name": "oaxaca", "stationcount": 38},
    {"name": "88.1 fm", "stationcount": 38},
    {"name": "bluegrass", "stationcount": 38},
    {"name": "r&b/urban", "stationcount": 38},
    {"name": "electropop", "stationcount": 38},
    {"name": "black metal", "stationcount": 38},
    {"name": "weihnachten", "stationcount": 38},
    {"name": "new classics", "stationcount": 38},
    {"name": "russian hits", "stationcount": 38},
    {"name": "smooth lounge", "stationcount": 38},
    {"name": "música latina", "stationcount": 38},
    {"name": "noticias regionales", "stationcount": 38},
    {"name": "chr", "stationcount": 37},
    {"name": "slow", "stationcount": 37},
    {"name": "german", "stationcount": 37},
    {"name": "english", "stationcount": 37},
    {"name": "spanish", "stationcount": 37},
    {"name": "100.3 fm", "stationcount": 37},
    {"name": "70 80 hits", "stationcount": 37},
    {"name": "vocal jazz", "stationcount": 37},
    {"name": "globalmedia", "stationcount": 37},
    {"name": "rock n roll", "stationcount": 37},
    {"name": "online radio", "stationcount": 37},
    {"name": "minimal techno", "stationcount": 37},
    {"name": "commercial-free", "stationcount": 37},
    {"name": "radio cristiana", "stationcount": 37},
    {"name": "conservative talk", "stationcount": 37},
    {"name": "танцевальная", "stationcount": 37},
    {"name": "uk", "stationcount": 36},
    {"name": "arts", "stationcount": 36},
    {"name": "drama", "stationcount": 36},
    {"name": "islam", "stationcount": 36},
    {"name": "disney", "stationcount": 36},
    {"name": "top100", "stationcount": 36},
    {"name": "éxitos", "stationcount": 36},
    {"name": "culiacán", "stationcount": 36},
    {"name": "post-punk", "stationcount": 36},
    {"name": "active rock", "stationcount": 36},
    {"name": "death metal", "stationcount": 36},
    {"name": "universidad", "stationcount": 36},
    {"name": "latinoamerica", "stationcount": 36},
    {"name": "greek folk music", "stationcount": 36},
    {"name": "bbc", "stationcount": 35},
    {"name": "j-pop", "stationcount": 35},
    {"name": "remix", "stationcount": 35},
    {"name": "95.3 fm", "stationcount": 35},
    {"name": "holiday", "stationcount": 35},
    {"name": "narodna", "stationcount": 35},
    {"name": "tabasco", "stationcount": 35},
    {"name": "variada", "stationcount": 35},
    {"name": "80s rock", "stationcount": 35},
    {"name": "clasicos", "stationcount": 35},
    {"name": "nu disco", "stationcount": 35},
    {"name": "soft pop", "stationcount": 35},
    {"name": "querétaro", "stationcount": 35},
    {"name": "soft music", "stationcount": 35},
    {"name": "classic jazz", "stationcount": 35},
    {"name": "villahermosa", "stationcount": 35},
    {"name": "sertanejo raiz", "stationcount": 35},
    {"name": "80", "stationcount": 34},
    {"name": "kpop", "stationcount": 34},
    {"name": "nayarit", "stationcount": 34},
    {"name": "darkwave", "stationcount": 34},
    {"name": "discofox", "stationcount": 34},
    {"name": "football", "stationcount": 34},
    {"name": "orthodox", "stationcount": 34},
    {"name": "synthwave", "stationcount": 34},
    {"name": "multimedios", "stationcount": 34},
    {"name": "adult alternative", "stationcount": 34},
    {"name": "spanish adult hits", "stationcount": 34},
    {"name": "san luis potosí city", "stationcount": 34},
    {"name": "00's", "stationcount": 33},
    {"name": "dutch", "stationcount": 33},
    {"name": "vocal", "stationcount": 33},
    {"name": "mérida", "stationcount": 33},
    {"name": "variado", "stationcount": 33},
    {"name": "clubbing", "stationcount": 33},
    {"name": "folclore", "stationcount": 33},
    {"name": "psytrance", "stationcount": 33},
    {"name": "hermosillo", "stationcount": 33},
    {"name": "puebla city", "stationcount": 33},
    {"name": "rock'n'roll", "stationcount": 33},
    {"name": "multilingual", "stationcount": 33},
    {"name": "quintana roo", "stationcount": 33},
    {"name": "latino américa", "stationcount": 33},
    {"name": "video game music", "stationcount": 33},
    {"name": "baladas en inglés", "stationcount": 33},
    {"name": "chansons françaises", "stationcount": 33},
    {"name": "10s", "stationcount": 32},
    {"name": "k-pop", "stationcount": 32},
    {"name": "lo-fi", "stationcount": 32},
    {"name": "latina", "stationcount": 32},
    {"name": "90.1 fm", "stationcount": 32},
    {"name": "96.1 fm", "stationcount": 32},
    {"name": "variedad", "stationcount": 32},
    {"name": "70s disco", "stationcount": 32},
    {"name": "comunitaria", "stationcount": 32},
    {"name": "greatest hits", "stationcount": 32},
    {"name": "ert", "stationcount": 31},
    {"name": "modern", "stationcount": 31},
    {"name": "99.7 fm", "stationcount": 31},
    {"name": "piraten", "stationcount": 31},
    {"name": "mexicali", "stationcount": 31},
    {"name": "mrcrosby", "stationcount": 31},
    {"name": "national", "stationcount": 31},
    {"name": "90s dance", "stationcount": 31},
    {"name": "argentina", "stationcount": 31},
    {"name": "folk rock", "stationcount": 31},
    {"name": "san diego", "stationcount": 31},
    {"name": "sertaneja", "stationcount": 31},
    {"name": "bossa nova", "stationcount": 31},
    {"name": "la comadre", "stationcount": 31},
    {"name": "jazz fusion", "stationcount": 31},
    {"name": "gospel music", "stationcount": 31},
    {"name": "storytelling", "stationcount": 31},
    {"name": "traffic information", "stationcount": 31},
    {"name": "soft", "stationcount": 30},
    {"name": "93.1 fm", "stationcount": 30},
    {"name": "chicago", "stationcount": 30},
    {"name": "art rock", "stationcount": 30},
    {"name": "grupo as", "stationcount": 30},
    {"name": "réunion", "stationcount": 30},
    {"name": "metalcore", "stationcount": 30},
    {"name": "government", "stationcount": 30},
    {"name": "orchestral", "stationcount": 30},
    {"name": "grupo siete", "stationcount": 30},
    {"name": "new country", "stationcount": 30},
    {"name": "radio fórmula primera cadena", "stationcount": 30},
    {"name": "orf", "stationcount": 29},
    {"name": "tamil", "stationcount": 29},
    {"name": "arabic", "stationcount": 29},
    {"name": "ethnic", "stationcount": 29},
    {"name": "tijuana", "stationcount": 29},
    {"name": "religios", "stationcount": 29},
    {"name": "orthodoxy", "stationcount": 29},
    {"name": "avant-garde", "stationcount": 29},
    {"name": "spoken word", "stationcount": 29},
    {"name": "geheimezender", "stationcount": 29},
    {"name": "christian praise&worship", "stationcount": 29},
    {"name": "90", "stationcount": 28},
    {"name": "bass", "stationcount": 28},
    {"name": "easy", "stationcount": 28},
    {"name": "m3u8", "stationcount": 28},
    {"name": "walm", "stationcount": 28},
    {"name": "jovem", "stationcount": 28},
    {"name": "celtic", "stationcount": 28},
    {"name": "92.1 fm", "stationcount": 28},
    {"name": "morelia", "stationcount": 28},
    {"name": "toronto", "stationcount": 28},
    {"name": "workout", "stationcount": 28},
    {"name": "japanese", "stationcount": 28},
    {"name": "torreón", "stationcount": 28},
    {"name": "disco funk", "stationcount": 28},
    {"name": "los mochis", "stationcount": 28},
    {"name": "party hits", "stationcount": 28},
    {"name": "reggaetón", "stationcount": 28},
    {"name": "rock music", "stationcount": 28},
    {"name": "modern rock", "stationcount": 28},
    {"name": "nachrichten", "stationcount": 28},
    {"name": "alternative pop", "stationcount": 28},
    {"name": "classical piano", "stationcount": 28},
    {"name": "mainstream rock", "stationcount": 28},
    {"name": "rhythm and blues", "stationcount": 28},
    {"name": "clasicos en ingles", "stationcount": 28},
    {"name": "contemporary hit radio", "stationcount": 28},
    {"name": "la hora de luis miguel", "stationcount": 28},
    {"name": "film", "stationcount": 27},
    {"name": "soca", "stationcount": 27},
    {"name": "movie", "stationcount": 27},
    {"name": "baroque", "stationcount": 27},
    {"name": "candela", "stationcount": 27},
    {"name": "podcast", "stationcount": 27},
    {"name": "101.3 fm", "stationcount": 27},
    {"name": "104.5 fm", "stationcount": 27},
    {"name": "business", "stationcount": 27},
    {"name": "córdoba", "stationcount": 27},
    {"name": "chrétien", "stationcount": 27},
    {"name": "glam rock", "stationcount": 27},
    {"name": "spiritual", "stationcount": 27},
    {"name": "evergreens", "stationcount": 27},
    {"name": "heavy rock", "stationcount": 27},
    {"name": "la poderosa", "stationcount": 27},
    {"name": "new york city", "stationcount": 27},
    {"name": "ciudad juárez", "stationcount": 27},
    {"name": "la nueva candela", "stationcount": 27},
    {"name": "la bestia grupera", "stationcount": 27},
    {"name": "grupo radio digital", "stationcount": 27},
    {"name": "calm", "stationcount": 26},
    {"name": "surf", "stationcount": 26},
    {"name": "jesus", "stationcount": 26},
    {"name": "roots", "stationcount": 26},
    {"name": "french", "stationcount": 26},
    {"name": "garage", "stationcount": 26},
    {"name": "guitar", "stationcount": 26},
    {"name": "nature", "stationcount": 26},
    {"name": "89.7 fm", "stationcount": 26},
    {"name": "95.7 fm", "stationcount": 26},
    {"name": "england", "stationcount": 26},
    {"name": "vintage", "stationcount": 26},
    {"name": "afrobeat", "stationcount": 26},
    {"name": "chiptune", "stationcount": 26},
    {"name": "esportes", "stationcount": 26},
    {"name": "cool jazz", "stationcount": 26},
    {"name": "lovesongs", "stationcount": 26},
    {"name": "only music", "stationcount": 26},
    {"name": "música religiosa", "stationcount": 26},
    {"name": "christian orthodox", "stationcount": 26},
    {"name": "лëгкая музыка", "stationcount": 26},
    {"name": "idm", "stationcount": 25},
    {"name": "dab+", "stationcount": 25},
    {"name": "etno", "stationcount": 25},
    {"name": "info", "stationcount": 25},
    {"name": "match", "stationcount": 25},
    {"name": "quran", "stationcount": 25},
    {"name": "r'n'b", "stationcount": 25},
    {"name": "tango", "stationcount": 25},
    {"name": "2000's", "stationcount": 25},
    {"name": "dj mix", "stationcount": 25},
    {"name": "health", "stationcount": 25},
    {"name": "mashup", "stationcount": 25},
    {"name": "89.3 fm", "stationcount": 25},
    {"name": "morelos", "stationcount": 25},
    {"name": "nu-jazz", "stationcount": 25},
    {"name": "107.9 fm", "stationcount": 25},
    {"name": "acapulco", "stationcount": 25},
    {"name": "campeche", "stationcount": 25},
    {"name": "mazatlán", "stationcount": 25},
    {"name": "oldschool", "stationcount": 25},
    {"name": "religiosa", "stationcount": 25},
    {"name": "album rock", "stationcount": 25},
    {"name": "free radio", "stationcount": 25},
    {"name": "non-profit", "stationcount": 25},
    {"name": "grupo pazos", "stationcount": 25},
    {"name": "sveriges radio", "stationcount": 25},
    {"name": "psychedelic rock", "stationcount": 25},
    {"name": "greek traditional", "stationcount": 25},
    {"name": "eclectic programming", "stationcount": 25},
    {"name": "beats", "stationcount": 24},
    {"name": "ibiza", "stationcount": 24},
    {"name": "musik", "stationcount": 24},
    {"name": "samba", "stationcount": 24},
    {"name": "celaya", "stationcount": 24},
    {"name": "motown", "stationcount": 24},
    {"name": "movies", "stationcount": 24},
    {"name": "88.5 fm", "stationcount": 24},
    {"name": "96.9 fm", "stationcount": 24},
    {"name": "dangdut", "stationcount": 24},
    {"name": "104.9 fm", "stationcount": 24},
    {"name": "amapiano", "stationcount": 24},
    {"name": "crooners", "stationcount": 24},
    {"name": "hot hits", "stationcount": 24},
    {"name": "paradise", "stationcount": 24},
    {"name": "rockabilly", "stationcount": 24},
    {"name": "funky house", "stationcount": 24},
    {"name": "rock & roll", "stationcount": 24},
    {"name": "freies radio", "stationcount": 24},
    {"name": "drum 'n' bass", "stationcount": 24},
    {"name": "turkish music", "stationcount": 24},
    {"name": "musica popular", "stationcount": 24},
    {"name": "piedras negras", "stationcount": 24},
    {"name": "nederlandstalig", "stationcount": 24},
    {"name": "internet station", "stationcount": 24},
    {"name": "instrumental music", "stationcount": 24},
    {"name": "ορθοδοξία", "stationcount": 24},
    {"name": "rave", "stationcount": 23},
    {"name": "drgnu", "stationcount": 23},
    {"name": "64kbps", "stationcount": 23},
    {"name": "bolero", "stationcount": 23},
    {"name": "fusion", "stationcount": 23},
    {"name": "humour", "stationcount": 23},
    {"name": "polish", "stationcount": 23},
    {"name": "92.5 fm", "stationcount": 23},
    {"name": "92.9 fm", "stationcount": 23},
    {"name": "99.9 fm", "stationcount": 23},
    {"name": "chanson", "stationcount": 23},
    {"name": "musical", "stationcount": 23},
    {"name": "student", "stationcount": 23},
    {"name": "fm globo", "stationcount": 23},
    {"name": "non-stop", "stationcount": 23},
    {"name": "breakbeat", "stationcount": 23},
    {"name": "disco polo", "stationcount": 23},
    {"name": "espiritual", "stationcount": 23},
    {"name": "piano jazz", "stationcount": 23},
    {"name": "hard techno", "stationcount": 23},
    {"name": "russian rock", "stationcount": 23},
    {"name": "pop en ingles", "stationcount": 23},
    {"name": "rock 'n' roll", "stationcount": 23},
    {"name": "state college", "stationcount": 23},
    {"name": "chihuahua city", "stationcount": 23},
    {"name": "ciudad obregón", "stationcount": 23},
    {"name": "puerto vallarta", "stationcount": 23},
    {"name": "nrm comunicaciones", "stationcount": 23},
    {"name": "progressive trance", "stationcount": 23},
    {"name": "classic rock oldies", "stationcount": 23},
    {"name": "gruperas del recuerdo", "stationcount": 23},
    {"name": "classic hits 60s 70a 80s", "stationcount": 23},
    {"name": "20s", "stationcount": 22},
    {"name": "vox", "stationcount": 22},
    {"name": "r.sa", "stationcount": 22},
    {"name": "queen", "stationcount": 22},
    {"name": "talks", "stationcount": 22},
    {"name": "540 am", "stationcount": 22},
    {"name": "varied", "stationcount": 22},
    {"name": "92.3 fm", "stationcount": 22},
    {"name": "musique", "stationcount": 22},
    {"name": "trip-hop", "stationcount": 22},
    {"name": "católica", "stationcount": 22},
    {"name": "notícias", "stationcount": 22},
    {"name": "buenisiima", "stationcount": 22},
    {"name": "euro disco", "stationcount": 22},
    {"name": "agriculture", "stationcount": 22},
    {"name": "tamil music", "stationcount": 22},
    {"name": "radio disney", "stationcount": 22},
    {"name": "nizhniy novgorod", "stationcount": 22},
    {"name": "baja california sur", "stationcount": 22},
    {"name": "urban adult contemporary", "stationcount": 22},
    {"name": "gold", "stationcount": 21},
    {"name": "iptv", "stationcount": 21},
    {"name": "1940s", "stationcount": 21},
    {"name": "drone", "stationcount": 21},
    {"name": "globo", "stationcount": 21},
    {"name": "space", "stationcount": 21},
    {"name": "global", "stationcount": 21},
    {"name": "89.9 fm", "stationcount": 21},
    {"name": "90.5 fm", "stationcount": 21},
    {"name": "anthems", "stationcount": 21},
    {"name": "folclor", "stationcount": 21},
    {"name": "la lupe", "stationcount": 21},
    {"name": "103.3 fm", "stationcount": 21},
    {"name": "103.9 fm", "stationcount": 21},
    {"name": "partymix", "stationcount": 21},
    {"name": "radio sa", "stationcount": 21},
    {"name": "romanian", "stationcount": 21},
    {"name": "religión", "stationcount": 21},
    {"name": "vaporwave", "stationcount": 21},
    {"name": "128 kbit/s", "stationcount": 21},
    {"name": "cuernavaca", "stationcount": 21},
    {"name": "film music", "stationcount": 21},
    {"name": "technology", "stationcount": 21},
    {"name": "deutschrock", "stationcount": 21},
    {"name": "indie music", "stationcount": 21},
    {"name": "thrash metal", "stationcount": 21},
    {"name": "popular music", "stationcount": 21},
    {"name": "southern rock", "stationcount": 21},
    {"name": "catholic radio", "stationcount": 21},
    {"name": "police scanner", "stationcount": 21},
    {"name": "radio publique", "stationcount": 21},
    {"name": "radio universal", "stationcount": 21},
    {"name": "radio communautaire", "stationcount": 21},
    {"name": "american forces network", "stationcount": 21},
    {"name": "best", "stationcount": 20},
    {"name": "roma", "stationcount": 20},
    {"name": "yoga", "stationcount": 20},
    {"name": "etnic", "stationcount": 20},
    {"name": "tepic", "stationcount": 20},
    {"name": "adulta", "stationcount": 20},
    {"name": "brasil", "stationcount": 20},
    {"name": "soccer", "stationcount": 20},
    {"name": "toluca", "stationcount": 20},
    {"name": "90.9 fm", "stationcount": 20},
    {"name": "91.7 fm", "stationcount": 20},
    {"name": "96.3 fm", "stationcount": 20},
    {"name": "boleros", "stationcount": 20},
    {"name": "cancún", "stationcount": 20},
    {"name": "deutsch", "stationcount": 20},
    {"name": "el paso", "stationcount": 20},
    {"name": "familia", "stationcount": 20},
    {"name": "handsup", "stationcount": 20},
    {"name": "scanner", "stationcount": 20},
    {"name": "103.7 fm", "stationcount": 20},
    {"name": "104.1 fm", "stationcount": 20},
    {"name": "106.1 fm", "stationcount": 20},
    {"name": "medieval", "stationcount": 20},
    {"name": "webradio", "stationcount": 20},
    {"name": "free jazz", "stationcount": 20},
    {"name": "hits 70's", "stationcount": 20},
    {"name": "rare groove", "stationcount": 20},
    {"name": "country rock", "stationcount": 20},
    {"name": "french music", "stationcount": 20},
    {"name": "luna de amor", "stationcount": 20},
    {"name": "business news", "stationcount": 20},
    {"name": "grupo radiosa", "stationcount": 20},
    {"name": "gómez palacio", "stationcount": 20},
    {"name": "united kingdom", "stationcount": 20},
    {"name": "querétaro city", "stationcount": 20},
    {"name": "musica cristiana", "stationcount": 20},
    {"name": "grupo promomedios", "stationcount": 20},
    {"name": "mensajes cristianos", "stationcount": 20},
    {"name": "radio reading service", "stationcount": 20},
    {"name": "contemporary christian", "stationcount": 20},
    {"name": "only the golden classics", "stationcount": 20},
    {"name": "rtbf", "stationcount": 19},
    {"name": "bebop", "stationcount": 19},
    {"name": "fresh", "stationcount": 19},
    {"name": "india", "stationcount": 19},
    {"name": "phonk", "stationcount": 19},
    {"name": "boston", "stationcount": 19},
    {"name": "breaks", "stationcount": 19},
    {"name": "vox fm", "stationcount": 19},
    {"name": "xalapa", "stationcount": 19},
    {"name": "98.1 fm", "stationcount": 19},
    {"name": "98.9 fm", "stationcount": 19},
    {"name": "zabavna", "stationcount": 19},
    {"name": "102.5 fm", "stationcount": 19},
    {"name": "102.9 fm", "stationcount": 19},
    {"name": "catolica", "stationcount": 19},
    {"name": "ecclesia", "stationcount": 19},
    {"name": "nacional", "stationcount": 19},
    {"name": "nu metal", "stationcount": 19},
    {"name": "uk garage", "stationcount": 19},
    {"name": "1980s hits", "stationcount": 19},
    {"name": "afro house", "stationcount": 19},
    {"name": "old school", "stationcount": 19},
    {"name": "los angeles", "stationcount": 19},
    {"name": "power metal", "stationcount": 19},
    {"name": "live concert", "stationcount": 19},
    {"name": "rogers media", "stationcount": 19},
    {"name": "latino urbano", "stationcount": 19},
    {"name": "5g智慧电台", "stationcount": 19},
    {"name": "christian talk", "stationcount": 19},
    {"name": "servicio social", "stationcount": 19},
    {"name": "videogame music", "stationcount": 19},
    {"name": "el heraldo radio", "stationcount": 19},
    {"name": "relaxation music", "stationcount": 19},
    {"name": "heraldo media group", "stationcount": 19},
    {"name": "grupo radio alegría", "stationcount": 19},
    {"name": "new format rebranding", "stationcount": 19},
    {"name": "электронная", "stationcount": 19},
    {"name": "actualidad", "stationcount": 18},
    {"name": "the beatles", "stationcount": 18},
    {"name": "classic hip hop", "stationcount": 18},
  ];
  List<String> tags = [];
  late List<String> searchTags;

  @override
  void initState() {
    for (Map s in raw) {
      tags.add(s['name']);
    }
    searchTags = tags;
    super.initState();
  }

  void search(String query) {
    if (query.isEmpty) {
      searchTags = tags;
    } else {
      searchTags = tags
          .where((item) => item.toLowerCase().startsWith(query.toLowerCase()))
          .toList();
    }
    setState(() {});
  }

  @override
  Widget build(BuildContext context) {
    return Directionality(
      textDirection: TextDirection.ltr,
      child: Dialog(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Column(
            children: [
              TextFieldBox(onChanged: search),
              Flexible(
                child: ListView.builder(
                  itemCount: searchTags.length,
                  itemBuilder: (BuildContext context, int index) {
                    return InkWell(
                      child: Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: TextView(searchTags[index]),
                      ),
                      onTap: () {
                        Navigator.pop(context, searchTags[index]);
                      },
                    );
                  },
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
