name: Manual Flutter Test & Build

on:
  workflow_dispatch:

jobs:
  flutter-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Doctor Licences
        run: yes | flutter doctor --android-licenses

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Flutter Analyze
        run: flutter pub get

      - name: Patch pdfrx
        run: |
          PDFRX_PATH=$(find $HOME/.pub-cache -type d -name "pdfium_flutter-*" | head -n 1)
          CMAKE_FILE="$PDFRX_PATH/android/CMakeLists.txt"

          if [ -f "$CMAKE_FILE" ]; then
            sed -i '2i add_link_options("LINKER:--build-id=none")' "$CMAKE_FILE"
            echo "Patched CMakeLists.txt in $CMAKE_FILE"
          else
            echo "CMakeLists.txt not found in expected location"
            exit 1
          fi

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Remove build folder
        run: rm -rf build/
